version: '3'

services:
  server:
    build: .
    user: '1000:1000'
    env_file:
      - .env
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - '5432:5432'
