version: '3'

services:
  server:
    image: 'marianobe/nc:${CIRCLE_SHA1}'
    user: '1000:1000'
    env_file:
      - .env
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - testdb

  db:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - '5432:5432'

  testdb:
    image: postgres:9.6
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
