version: '3'

services:
  server:
    image: 'marianobe/nc:${CIRCLE_SHA1}'
    container_name: server
    env_file:
      - .env
    environment:
      JEST_JUNIT_OUTPUT: '/tmp/js-test-results.xml'
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      COVERALLS_SERVICE_NAME: ${COVERALLS_SERVICE_NAME}
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - db
      - testdb

  db:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - '5432:5432'

  testdb:
    image: postgres:9.6
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
