version: 2

jobs:
  build:
    working_directory: ~/natural-cycles-challenge
    docker:
      - image: circleci/node:10.12-jessie
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull marianobe/nc
            docker pull node:10-alpine
            docker build --cache-from marianobe/nc,node:10-alpine -f Dockerfile-test -t nc:$CIRCLE_SHA1 .
            docker tag nc:$CIRCLE_SHA1 marianobe/nc:$CIRCLE_SHA1
            docker tag nc:$CIRCLE_SHA1 marianobe/nc:latest
            docker push marianobe/nc:$CIRCLE_SHA1
            docker push marianobe/nc:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-compose.circleci.yml
            - .env
            - now.json
            - Dockerfile
            - build
            - src
            - client

  test:
    working_directory: ~/natural-cycles-challenge
    docker:
      - image: circleci/node:10.12-jessie
    steps:
      - attach_workspace:
          at: ~/natural-cycles-challenge
      - setup_remote_docker
      - run:
          name: Pull images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull marianobe/nc:$CIRCLE_SHA1
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.circleci.yml up -d
            sleep 15
            docker-compose -f docker-compose.circleci.yml exec server /bin/ash -c "node_modules/.bin/jest --ci --reporters=default --reporters=jest-junit --runInBand --coverage --coverageDirectory=/tmp/coverage && cat /tmp/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
      - run:
          name: Get test results
          when: always
          command: |
            mkdir ~/test_results
            docker cp "$(docker ps --filter="name=server" -q)":/tmp/js-test-results.xml ~/test_results/js-test-results.xml
            docker cp "$(docker ps --filter="name=server" -q)":/tmp/coverage ~/test_results/coverage
      - store_test_results:
          path: ~/test_results
      - store_artifacts:
          path: ~/test_results

  deploy:
    working_directory: ~/natural-cycles-challenge
    docker:
      - image: circleci/node:10.12-jessie
    steps:
      - attach_workspace:
          at: ~/natural-cycles-challenge
      - run:
          name: Now deploy
          command: |
            sudo npm i -g --unsafe-perm now
            now --public -t $NOW_TOKEN && now -t $NOW_TOKEN alias nc-mariano

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
