version: 2

jobs:
  build:
    working_directory: ~/natural-cycles-challenge
    docker:
      - image: circleci/node:10.12-jessie
    steps:
      - checkout
      - run:
          name: Build frontend
          command: |
            cd client && sudo npm i -g @angular/cli && npm ci && npm run build
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build --cache-from marianobe/nc,marianobe/node-base -f Dockerfile -t nc:$CIRCLE_SHA1 .
            docker tag nc:$CIRCLE_SHA1 marianobe/nc:$CIRCLE_SHA1
            docker tag nc:$CIRCLE_SHA1 marianobe/nc:latest
            docker push marianobe/nc:$CIRCLE_SHA1
            docker push marianobe/nc:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
